import type { SiteContent } from "./types";

export const en: SiteContent = {
  person: {
    name: "Juan David Guzmán",
    shortName: "JDG",
    role: "Structural & Systems Engineer",
    location: "Rosario, Argentina",
    email: "ing.guzmanjuandavid@gmail.com",
    phone: "+54 341 360-3215",
    whatsappUrl: "https://wa.me/5493413603215",
    linkedinUrl: "https://linkedin.com/in/ingjdg",
    careerStart: "2021-08",
  },
  about: {
    paragraphs: [
      "I'm a Civil Engineer specialized in structures, with over 5 years of experience on large-scale industrial projects: oil extraction plants, port terminals and storage silos, for clients such as Cargill, Louis Dreyfus Company, Terminal 6 and COFCO.",
      "I'm currently a Steel Structures Calculation Engineer at Flexio, where I cover the full project cycle. Among other projects, I'm leading the futsal micro-stadium for Jockey Club de Rosario: around 100 tons of steel plus reinforced concrete infrastructure, with basic and detail engineering, 3D modeling, fabrication and erection drawings, and direct client relationship throughout the process.",
      "My edge is a hybrid profile: beyond calculating, I build the tools to do it better. I work on interoperability between SAP2000, IDEA StatiCa and Tekla Structures to move a model from analysis to fabrication drawings with minimal friction, and I design my own management systems with Python, Firebase and Google Apps Script. I'm also currently designing and operating a custom AI agent infrastructure running 24/7, which I use to speed up engineering, development and management tasks.",
      "I've been teaching Applied Statics at the Engineering School of Universidad Nacional de Rosario since 2022, and hold a Cambridge-certified B2 English level.",
    ],
  },
  stats: [
    { id: "years", value: 0, labelKey: "yearsExperience" },
    { id: "steel", value: 7500, suffix: "+ t", labelKey: "steelTons" },
    { id: "concrete", value: 75000, suffix: "+ m³", labelKey: "concreteM3" },
    { id: "clients", value: 4, labelKey: "industrialClients" },
    { id: "projects", value: 18, suffix: "+", labelKey: "ownProjects" },
  ],
  experience: [
    {
      id: "flexio",
      role: "Steel Structures Calculation Engineer",
      company: "Flexio",
      location: "Rosario, Argentina",
      startDate: "2026-07",
      endDate: null,
      summary:
        "Full-scope role: basic and detail engineering, 3D modeling and fabrication. Direct management of assigned projects with hands-on client relationships.",
      highlights: [
        "Futsal micro-stadium — Jockey Club de Rosario: ~100 t of steel + reinforced concrete infrastructure. Basic and detail engineering, fabrication and erection drawings, direct client relationship.",
        "Steel portal frame for load testing: calculation and fabrication.",
        "Introduced calculation-optimization improvements to the technical office.",
      ],
    },
    {
      id: "excel_consulting",
      role: "Structural Engineer",
      company: "Excel Consulting",
      location: "Rosario, Argentina",
      startDate: "2024-01",
      endDate: "2026-06",
      summary:
        "Industrial engineering for agribusiness and energy. Clients: Cargill, Terminal 6, Louis Dreyfus Company, COFCO.",
      highlights: [
        "Design and calculation of steel and concrete structures for oil extraction plants, port terminals and silos.",
        "Calculation reports, technical specifications and drawings across basic, detail, fabrication and erection engineering. CIRSOC and international standards (Tekla Structures, SAP2000, RFEM).",
        "Technical audit and validation of contractors' calculation reports and proposals.",
        "Quantity take-offs and ±30% CAPEX estimates for full industrial plants: Louis Dreyfus Company (5,000 t of steel, 50,000 m³ of concrete) and Terminales y Servicios (2,500 t of steel, 25,000 m³ of concrete).",
        "Pre-sizing of a 200,000 t storage cell for Cargill Brazil.",
        "Built in-house engineering tools (Python and Excel VBA) that cut 8-hour tasks down to seconds.",
      ],
    },
    {
      id: "ac_ingenieria",
      role: "Structural Engineer",
      company: "AC Ingeniería",
      location: "Rosario, Argentina",
      startDate: "2023-03",
      endDate: "2023-12",
      summary: "Structural calculation for road and light industrial infrastructure.",
      highlights: [
        "34 m tall steel stair tower attached to an existing concrete structure, 3-stage erection, 12 t of steel (SAP2000).",
        "Calculation, drawings and fabrication control for road signage gantries.",
        "Calculation, drawings and fabrication supervision of precast concrete elements (400 m²) for Neostar.",
      ],
    },
    {
      id: "deprop",
      role: "Civil Engineer",
      company: "Deprop SRL",
      location: "Rosario, Argentina",
      startDate: "2021-08",
      endDate: "2023-02",
      summary: "Calculation, drawings and site supervision for public and private works.",
      highlights: [
        "Underpinning and expansion of Banco Nación in Firmat: calculation and supervision of underpinning for differential settlement of an in-service institutional building; mixed concrete + steel roof expansion on piles.",
        "Structural calculation, drawings and supervision for public school classrooms, a kindergarten, and a mixed-structure house on piles.",
        "Demolition and lintel work for a commercial premises: reinforcement calculation, execution drawings and site follow-up.",
      ],
    },
    {
      id: "pilotes_pasantia",
      role: "Engineering Intern",
      company: "Ingeniería y Pilotes",
      location: "Rosario, Argentina",
      startDate: "2021-03",
      endDate: "2021-06",
      summary: "First professional experience on site.",
      highlights: [
        "Site supervision of pile foundations for an industrial building.",
        "Prepared the qualification file for the Provincial Bidders Registry.",
      ],
    },
  ],
  projects: [
    {
      id: "flexio_jockey_club",
      track: "structural",
      name: "Futsal Micro-Stadium — Jockey Club de Rosario",
      role: "Basic & detail engineering, project management",
      client: "Jockey Club de Rosario",
      date: "2026",
      description:
        "Roughly 100 tons of steel structure plus reinforced concrete infrastructure for a futsal micro-stadium. Full scope: basic and detail engineering, 3D modeling, fabrication and erection drawings, and direct client relationship throughout the project.",
      highlights: [
        "~100 t of steel structure + reinforced concrete infrastructure",
        "Basic, detail, fabrication and erection engineering",
        "Direct client management",
      ],
      stack: ["SAP2000", "Tekla Structures", "IDEA StatiCa", "CIRSOC"],
      featured: true,
      image: null,
    },
    {
      id: "ac_molinos_agro",
      track: "structural",
      name: "Industrial Building — Molinos Agro",
      role: "Structural Engineer — AC Ingeniería",
      client: "Molinos Agro",
      date: "2023",
      description:
        "Calculation and drawings for an industrial steel structure for Molinos Agro, with on-site erection follow-up.",
      stack: ["SAP2000", "AutoCAD"],
      image: null,
      videoUrl: "https://youtu.be/65POO6vR_nY",
    },
    {
      id: "excel_celda_cargill_brasil",
      track: "structural",
      name: "200,000 t Storage Cell Pre-Sizing — Cargill Brazil",
      client: "Cargill",
      date: "2026",
      description:
        "Structural pre-sizing of a 200,000-ton storage cell with an excavated base on piles. Followed by formwork drawings for bidding.",
      stack: ["Reinforced concrete", "Pile foundations"],
      image: null,
    },
    {
      id: "excel_nave_cargill",
      track: "structural",
      name: "Truck Unloading Building Retrofit — Cargill",
      client: "Cargill",
      date: "2026",
      description:
        "Platform tower attached to an existing structure to support and inspect a new duct, plus an interior bridge for truck weighing. SAP2000 calculation and Tekla Structures detail model for fabrication drawings.",
      stack: ["SAP2000", "Tekla Structures"],
      image: null,
    },
    {
      id: "galassi_kcc",
      track: "structural",
      name: "Club House Rehabilitation — Kentucky Club de Campo",
      role: "Independent technical collaboration",
      date: "2023",
      description:
        "Fully fire-damaged building. Post-incident structural survey, reinforcement calculation, new timber roof, foundations and full site supervision from day one.",
      stack: ["Reinforced concrete", "Structural rehabilitation"],
      image: null,
    },
    {
      id: "deprop_bna_firmat",
      track: "structural",
      name: "Underpinning & Expansion — Banco Nación Firmat",
      client: "Banco Nación",
      date: "2022",
      description:
        "Underpinning for differential settlement of an in-service institutional building, plus an expansion with a new mixed concrete + steel roof building built on piles.",
      stack: ["Reinforced concrete", "Foundations", "Underpinning"],
      image: null,
    },
    {
      id: "bim_interoperability",
      track: "systems",
      name: "BIM Interoperability — SAP2000 · IDEA StatiCa · Tekla Structures",
      role: "Own workflow",
      date: "Ongoing",
      description:
        "A workflow connecting structural analysis (SAP2000), connection design (IDEA StatiCa) and detail modeling (Tekla Structures) to take a project from calculation to fabrication drawings with minimal friction and rework.",
      stack: ["SAP2000", "IDEA StatiCa", "Tekla Structures"],
      featured: true,
      image: null,
    },
    {
      id: "ai_agents_orchestration",
      track: "systems",
      name: "AI Agent Orchestration — 24/7 Infrastructure",
      role: "Design and operation",
      date: "Ongoing",
      description:
        "A custom AI agent system deployed on a VPS, running continuously to automate development, technical analysis and management tasks. Modular architecture built for autonomy and operational robustness.",
      stack: ["Claude", "Automation", "24/7 VPS"],
      featured: true,
      image: null,
      draft: true,
    },
    {
      id: "area_viva",
      track: "systems",
      name: "Management & Quoting Platform — AREA VIVA",
      role: "End-to-end design and development",
      client: "AREA VIVA",
      date: "2026",
      description:
        "Web platform for commercial, budgeting and operational management of interior design and furnishing projects: clients, suppliers, catalog, quotes, documents and delivery tracking. Authentication, autosave, versioned PDF generation and Google Drive integration.",
      highlights: [
        "Unified data model for clients, suppliers, items, projects and quotes",
        "Four document outputs generated automatically, with images and a tracking checklist",
        "Versioned PDF architecture with invalidation on relevant changes",
      ],
      stack: ["Firebase Auth", "Cloud Firestore", "Firebase Hosting", "JavaScript", "Google Drive", "html2pdf.js"],
      image: null,
    },
    {
      id: "software_ingenieria_excel",
      track: "systems",
      name: "In-House Engineering Tools Suite",
      role: "Design and development",
      client: "Excel Consulting",
      date: "2024–2026",
      description:
        "A set of Python and Excel VBA tools to speed up structural calculation in the technical office: a dynamic industrial equipment database, calculation apps, and automation of repetitive processes.",
      highlights: ["Automations that cut 8-hour tasks down to seconds"],
      stack: ["Python", "Excel VBA"],
      image: null,
    },
  ],
  skills: [
    {
      id: "structural",
      nameKey: "categoryStructural",
      description:
        "Steel and reinforced concrete structures under CIRSOC, AISC and ACI codes, across every stage: conceptual, basic, detail, fabrication and erection.",
      tags: [
        { name: "CIRSOC", highlight: true },
        { name: "AISC", highlight: true },
        { name: "ACI", highlight: true },
        { name: "SAP2000", highlight: true },
        { name: "IDEA StatiCa", highlight: true },
        { name: "Tekla Structures", highlight: true },
        { name: "STAAD.Pro" },
        { name: "RFEM" },
        { name: "AutoCAD 2D/3D" },
        { name: "BIM Modeling" },
      ],
    },
    {
      id: "systems",
      nameKey: "categorySystems",
      description:
        "Data architecture, operational interfaces and automation, from in-house tools to full web products and AI agent orchestration.",
      tags: [
        { name: "AI Automation", highlight: true },
        { name: "Google Apps Script", highlight: true },
        { name: "Python", highlight: true },
        { name: "Firebase", highlight: true },
        { name: "Cloud Firestore", highlight: true },
        { name: "JavaScript", highlight: true },
        { name: "Data architecture", highlight: true },
        { name: "Excel VBA" },
        { name: "AppSheet" },
        { name: "Looker Studio" },
        { name: "Google Drive API" },
        { name: "GitHub Pages" },
      ],
    },
  ],
  education: [
    {
      id: "edu_especializacion",
      title: "Specialization in Structural Engineering",
      institution: "Universidad Nacional de Rosario (UNR)",
      location: "Rosario, Argentina",
      startYear: 2023,
      endYear: 2024,
      type: "postgraduate",
    },
    {
      id: "edu_civil",
      title: "Civil Engineering",
      institution: "Universidad Nacional de Rosario (UNR)",
      location: "Rosario, Argentina",
      startYear: 2015,
      endYear: 2021,
      type: "degree",
    },
    {
      id: "unr_docente",
      title: "Lecturer — Applied Statics",
      institution: "Universidad Nacional de Rosario (UNR)",
      location: "Rosario, Argentina",
      startYear: 2022,
      endYear: null,
      type: "teaching",
      detail: "Practical Statics classes for the Civil Engineering program.",
    },
    {
      id: "cambridge_english",
      title: "Cambridge English: First (B2)",
      institution: "Cambridge Assessment English",
      location: "",
      startYear: 0,
      endYear: null,
      type: "certification",
    },
  ],
  languages: [
    { language: "Spanish", level: "Native" },
    { language: "English", level: "B2", certification: "Cambridge" },
  ],
};
