import type { SiteContent } from "./types";

export const es: SiteContent = {
  person: {
    name: "Juan David Guzmán",
    shortName: "JDG",
    role: "Ingeniero en Estructuras & Sistemas",
    location: "Rosario, Argentina",
    email: "ing.guzmanjuandavid@gmail.com",
    phone: "+54 341 360-3215",
    whatsappUrl: "https://wa.me/5493413603215",
    linkedinUrl: "https://linkedin.com/in/ingjdg",
    careerStart: "2021-08",
  },
  about: {
    paragraphs: [
      "Soy Ingeniero Civil especializado en estructuras, con más de 5 años de experiencia en proyectos industriales de gran escala: plantas de extracción de aceite, terminales portuarias y silos de almacenamiento, para clientes como Cargill, Louis Dreyfus Company, Terminal 6 y COFCO.",
      "Hoy soy Calculista de Estructuras Metálicas en Flexio, donde cubro el ciclo completo de proyecto. Estoy a cargo, entre otros, del microestadio de futsal del Jockey Club de Rosario: alrededor de 100 toneladas de acero más infraestructura de hormigón armado, con ingeniería básica y de detalle, modelado 3D, planos de fabricación y montaje, y trato directo con el cliente durante todo el proceso.",
      "Mi diferencial es un perfil híbrido: además de calcular, construyo las herramientas para hacerlo mejor. Trabajo la interoperabilidad entre SAP2000, IDEA StatiCa y Tekla Structures para llevar un modelo desde el análisis hasta el plano de fabricación sin fricción, y diseño mis propios sistemas de gestión con Python, Firebase y Google Apps Script. Actualmente además diseño y opero una infraestructura propia de agentes de inteligencia artificial corriendo 24/7, que uso para acelerar tareas de ingeniería, desarrollo y gestión.",
      "Soy docente de Estática Aplicada en la Facultad de Ingeniería de la Universidad Nacional de Rosario desde 2022, e inglés B2 certificado por Cambridge.",
    ],
  },
  stats: [
    { id: "years", value: 0, labelKey: "yearsExperience" },
    { id: "steel", value: 7500, suffix: "+ t", labelKey: "steelTons" },
    { id: "concrete", value: 75000, suffix: "+ m³", labelKey: "concreteM3" },
    { id: "clients", value: 4, labelKey: "industrialClients" },
    { id: "projects", value: 18, suffix: "+", labelKey: "ownProjects" },
  ],
  experience: [
    {
      id: "flexio",
      role: "Calculista de Estructuras Metálicas",
      company: "Flexio",
      location: "Rosario, Argentina",
      startDate: "2026-07",
      endDate: null,
      summary:
        "Rol integral: ingeniería básica y de detalle, modelado 3D y fabricación. Gestión propia de obras con trato directo con clientes.",
      highlights: [
        "Microestadio de futsal — Jockey Club de Rosario: ~100 t de acero + infraestructura de hormigón armado. Ingeniería básica y de detalle, planos de fabricación y montaje, relación directa con el cliente.",
        "Pórtico metálico para ensayos de cargas: cálculo y fabricación.",
        "Incorporación de innovaciones de optimización de cálculo a la oficina técnica.",
      ],
    },
    {
      id: "excel_consulting",
      role: "Ingeniero Estructural",
      company: "Excel Consulting",
      location: "Rosario, Argentina",
      startDate: "2024-01",
      endDate: "2026-06",
      summary:
        "Ingeniería industrial para agroindustria y energía. Clientes: Cargill, Terminal 6, Louis Dreyfus Company, COFCO.",
      highlights: [
        "Diseño y cálculo de estructuras metálicas y de hormigón para plantas de extracción de aceite, terminales portuarias y silos.",
        "Memorias de cálculo, especificaciones técnicas y planos en ingeniería básica, detalle, fabricación y montaje. CIRSOC y estándares internacionales (Tekla Structures, SAP2000, RFEM).",
        "Auditoría y validación técnica de memorias de cálculo y propuestas de contratistas.",
        "Cómputos métricos y estimaciones CAPEX ±30% de plantas industriales completas: Louis Dreyfus Company (5.000 t de acero, 50.000 m³ de hormigón) y Terminales y Servicios (2.500 t de acero, 25.000 m³ de hormigón).",
        "Predimensionamiento de celda de almacenamiento de 200.000 t para Cargill Brasil.",
        "Desarrollo de herramientas propias de ingeniería (Python y Excel VBA) que redujeron tareas de 8 horas a segundos.",
      ],
    },
    {
      id: "ac_ingenieria",
      role: "Ingeniero Estructural",
      company: "AC Ingeniería",
      location: "Rosario, Argentina",
      startDate: "2023-03",
      endDate: "2023-12",
      summary: "Cálculo estructural para infraestructura vial e industrial liviana.",
      highlights: [
        "Torre de escalera metálica de 34 m adosada a estructura de hormigón existente, montaje en 3 etapas, 12 t de acero (SAP2000).",
        "Cálculo, planos y control de fabricación de banderolas y pórticos viales.",
        "Cálculo, planos y supervisión de fabricación de prefabricados de hormigón armado (400 m²) para Neostar.",
      ],
    },
    {
      id: "deprop",
      role: "Ingeniero Civil",
      company: "Deprop SRL",
      location: "Rosario, Argentina",
      startDate: "2021-08",
      endDate: "2023-02",
      summary: "Cálculo, planos y supervisión de obras públicas y privadas.",
      highlights: [
        "Recalce y ampliación del Banco Nación de Firmat: cálculo y supervisión de recalce por hundimiento diferencial de edificio institucional en servicio, ampliación mixta hormigón + cubierta metálica sobre pilotes.",
        "Cálculo estructural, planos y supervisión de aulas para escuela pública, jardín de infantes y vivienda de estructura mixta sobre pilotes.",
        "Demolición y adintelamiento de local comercial: cálculo de refuerzos, planos de ejecución y seguimiento de obra.",
      ],
    },
    {
      id: "pilotes_pasantia",
      role: "Pasante de Ingeniería",
      company: "Ingeniería y Pilotes",
      location: "Rosario, Argentina",
      startDate: "2021-03",
      endDate: "2021-06",
      summary: "Primera experiencia profesional en obra.",
      highlights: [
        "Supervisión de obra de fundaciones con pilotes para nave industrial.",
        "Armado de legajo para habilitación en Registro de Licitadores Provinciales.",
      ],
    },
  ],
  projects: [
    {
      id: "flexio_jockey_club",
      track: "structural",
      name: "Microestadio de Futsal — Jockey Club de Rosario",
      role: "Ingeniería básica, de detalle y gestión",
      client: "Jockey Club de Rosario",
      date: "2026",
      description:
        "Estructura metálica de aproximadamente 100 toneladas más infraestructura de hormigón armado para un microestadio de futsal. Alcance integral: ingeniería básica y de detalle, modelado 3D, planos de fabricación y montaje, y relación directa con el cliente durante todo el proyecto.",
      highlights: [
        "~100 t de estructura metálica + infraestructura de hormigón armado",
        "Ingeniería básica, de detalle, fabricación y montaje",
        "Gestión directa con el cliente",
      ],
      stack: ["SAP2000", "Tekla Structures", "IDEA StatiCa", "CIRSOC"],
      featured: true,
      image: null,
    },
    {
      id: "ac_molinos_agro",
      track: "structural",
      name: "Nave Industrial — Molinos Agro",
      role: "Ingeniero Estructural — AC Ingeniería",
      client: "Molinos Agro",
      date: "2023",
      description:
        "Cálculo y planos de estructura metálica industrial para Molinos Agro, con seguimiento del montaje en obra.",
      stack: ["SAP2000", "AutoCAD"],
      image: null,
      videoUrl: "https://youtu.be/65POO6vR_nY",
    },
    {
      id: "excel_celda_cargill_brasil",
      track: "structural",
      name: "Predimensionamiento de Celda de 200.000 t — Cargill Brasil",
      client: "Cargill",
      date: "2026",
      description:
        "Predimensionamiento estructural de una celda de almacenamiento de 200.000 toneladas con fondo cavado sobre pilotes. Desarrollo posterior de planos de encofrado para cotización.",
      stack: ["Hormigón armado", "Fundaciones sobre pilotes"],
      image: null,
    },
    {
      id: "excel_nave_cargill",
      track: "structural",
      name: "Reforma de Nave para Descarga de Camiones — Cargill",
      client: "Cargill",
      date: "2026",
      description:
        "Torre con plataforma adosada a estructura existente para soporte e inspección de un nuevo ducto, más puente interior para el calado de camiones. Cálculo en SAP2000 y modelo de detalle en Tekla Structures para planos de fabricación.",
      stack: ["SAP2000", "Tekla Structures"],
      image: null,
    },
    {
      id: "galassi_kcc",
      track: "structural",
      name: "Rehabilitación Club House — Kentucky Club de Campo",
      role: "Colaboración técnica independiente",
      date: "2023",
      description:
        "Edificio completamente incendiado. Relevamiento del estado estructural post-siniestro, cálculo de refuerzos, nueva cubierta de madera, fundaciones y supervisión integral de la obra completa desde el día 1.",
      stack: ["Hormigón armado", "Rehabilitación estructural"],
      image: null,
    },
    {
      id: "deprop_bna_firmat",
      track: "structural",
      name: "Recalce y Ampliación — Banco Nación Firmat",
      client: "Banco Nación",
      date: "2022",
      description:
        "Recalce por hundimiento diferencial de un edificio institucional en servicio, y ampliación con nuevo edificio mixto hormigón + cubierta metálica ejecutado sobre pilotes.",
      stack: ["Hormigón armado", "Fundaciones", "Recalce estructural"],
      image: null,
    },
    {
      id: "bim_interoperability",
      track: "systems",
      name: "Interoperabilidad BIM — SAP2000 · IDEA StatiCa · Tekla Structures",
      role: "Flujo de trabajo propio",
      date: "En curso",
      description:
        "Flujo de trabajo que conecta el análisis estructural (SAP2000), la verificación de conexiones (IDEA StatiCa) y el modelado de detalle (Tekla Structures) para llevar un proyecto del cálculo al plano de fabricación con la menor fricción y reproceso posibles.",
      stack: ["SAP2000", "IDEA StatiCa", "Tekla Structures"],
      featured: true,
      image: null,
    },
    {
      id: "ai_agents_orchestration",
      track: "systems",
      name: "Orquestación de Agentes de IA — Infraestructura 24/7",
      role: "Diseño y operación",
      date: "En curso",
      description:
        "Sistema propio de agentes de inteligencia artificial desplegado en un VPS, funcionando de forma continua para automatizar tareas de desarrollo, análisis técnico y gestión. Arquitectura modular orientada a autonomía y robustez operativa.",
      stack: ["Claude", "Automatización", "VPS 24/7"],
      featured: true,
      image: null,
      draft: true,
    },
    {
      id: "area_viva",
      track: "systems",
      name: "Sistema Integral de Gestión y Presupuestos — AREA VIVA",
      role: "Diseño y desarrollo integral",
      client: "AREA VIVA",
      date: "2026",
      description:
        "Plataforma web para gestión comercial, presupuestaria y operativa de proyectos de interiorismo y amoblamiento: clientes, proveedores, catálogo, presupuestos, documentos y seguimiento hasta entrega. Autenticación, autosave, generación de PDFs versionados e integración con Google Drive.",
      highlights: [
        "Modelo de datos unificado para clientes, proveedores, artículos, proyectos y presupuestos",
        "Cuatro salidas documentales generadas automáticamente, con imágenes y checklist de seguimiento",
        "Arquitectura de PDFs versionados con invalidación por cambios relevantes",
      ],
      stack: ["Firebase Auth", "Cloud Firestore", "Firebase Hosting", "JavaScript", "Google Drive", "html2pdf.js"],
      image: null,
    },
    {
      id: "software_ingenieria_excel",
      track: "systems",
      name: "Suite de Herramientas de Ingeniería Interna",
      role: "Diseño y desarrollo",
      client: "Excel Consulting",
      date: "2024–2026",
      description:
        "Conjunto de herramientas en Python y Excel VBA para agilizar el cálculo estructural en oficina técnica: base de datos dinámica de equipos industriales, aplicaciones de cálculo y automatización de procesos repetitivos.",
      highlights: ["Automatizaciones que redujeron tareas de 8 horas a segundos"],
      stack: ["Python", "Excel VBA"],
      image: null,
    },
  ],
  skills: [
    {
      id: "structural",
      nameKey: "categoryStructural",
      description:
        "Estructuras de acero y hormigón armado bajo normativas CIRSOC, AISC y ACI, en todas las etapas: conceptual, básica, detalle, fabricación y montaje.",
      tags: [
        { name: "CIRSOC", highlight: true },
        { name: "AISC", highlight: true },
        { name: "ACI", highlight: true },
        { name: "SAP2000", highlight: true },
        { name: "IDEA StatiCa", highlight: true },
        { name: "Tekla Structures", highlight: true },
        { name: "STAAD.Pro" },
        { name: "RFEM" },
        { name: "AutoCAD 2D/3D" },
        { name: "Modelado BIM" },
      ],
    },
    {
      id: "systems",
      nameKey: "categorySystems",
      description:
        "Arquitectura de datos, interfaces operativas y automatización, desde herramientas internas hasta productos web completos y orquestación de agentes de IA.",
      tags: [
        { name: "Automatización con IA", highlight: true },
        { name: "Google Apps Script", highlight: true },
        { name: "Python", highlight: true },
        { name: "Firebase", highlight: true },
        { name: "Cloud Firestore", highlight: true },
        { name: "JavaScript", highlight: true },
        { name: "Arquitectura de datos", highlight: true },
        { name: "Excel VBA" },
        { name: "AppSheet" },
        { name: "Looker Studio" },
        { name: "Google Drive API" },
        { name: "GitHub Pages" },
      ],
    },
  ],
  education: [
    {
      id: "edu_especializacion",
      title: "Especialización en Ingeniería Estructural",
      institution: "Universidad Nacional de Rosario (UNR)",
      location: "Rosario, Argentina",
      startYear: 2023,
      endYear: 2024,
      type: "postgraduate",
    },
    {
      id: "edu_civil",
      title: "Ingeniería Civil",
      institution: "Universidad Nacional de Rosario (UNR)",
      location: "Rosario, Argentina",
      startYear: 2015,
      endYear: 2021,
      type: "degree",
    },
    {
      id: "unr_docente",
      title: "Docente — Estática Aplicada",
      institution: "Universidad Nacional de Rosario (UNR)",
      location: "Rosario, Argentina",
      startYear: 2022,
      endYear: null,
      type: "teaching",
      detail: "Clases prácticas de Estática en la carrera de Ingeniería Civil.",
    },
    {
      id: "cambridge_english",
      title: "Cambridge English: First (B2)",
      institution: "Cambridge Assessment English",
      location: "",
      startYear: 0,
      endYear: null,
      type: "certification",
    },
  ],
  languages: [
    { language: "Español", level: "Nativo" },
    { language: "Inglés", level: "B2", certification: "Cambridge" },
  ],
};
